// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationnementAPI.Data.Context;

#nullable disable

namespace StationnementAPI.Migrations
{
    [DbContext(typeof(StationnementDbContext))]
    [Migration("20250217001137_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StationnementAPI.Models.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("UtilisateurId1");

                    b.ToTable("Abonnement", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TaxeFederal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TaxeProvincial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Configuration", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbonnementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TarificationId")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId")
                        .IsUnique();

                    b.HasIndex("TarificationId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Paiement", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Tarification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DureeMax")
                        .HasColumnType("int");

                    b.Property<int>("DureeMin")
                        .HasColumnType("int");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Tarification", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EstConverti")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstPaye")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TempsArrive")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TempsSortie")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeId")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(205)
                        .HasColumnType("varchar(205)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(205)
                        .HasColumnType("varchar(205)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(205)
                        .HasColumnType("varchar(205)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(205)
                        .HasColumnType("varchar(205)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("StationnementAPI.Models.Abonnement", b =>
                {
                    b.HasOne("StationnementAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationnementAPI.Models.Utilisateur", null)
                        .WithMany("Abonnements")
                        .HasForeignKey("UtilisateurId1");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("StationnementAPI.Models.Configuration", b =>
                {
                    b.HasOne("StationnementAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("StationnementAPI.Models.Paiement", b =>
                {
                    b.HasOne("StationnementAPI.Models.Abonnement", "Abonnement")
                        .WithOne()
                        .HasForeignKey("StationnementAPI.Models.Paiement", "AbonnementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StationnementAPI.Models.Tarification", "Tarification")
                        .WithMany()
                        .HasForeignKey("TarificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StationnementAPI.Models.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("StationnementAPI.Models.Paiement", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Abonnement");

                    b.Navigation("Tarification");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("StationnementAPI.Models.Utilisateur", b =>
                {
                    b.Navigation("Abonnements");
                });
#pragma warning restore 612, 618
        }
    }
}
